[package]
name = "solomonhawk"
version = "0.1.0"
edition = "2021"
authors = ["Solomon Hawk <solomon.hawk@viget.com>"]

[workspace]
members = ["src/*", "target/aoc/aoc-autobuild"]

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
