name: CI

on:
  pull_request:
  # run jobs on merges to main, allowing PR branches to see shared caches
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo $GITHUB_REF

  solomonhawk-build:
    if: startsWith(github.ref, 'refs/heads/sfh/') || startsWith(github.ref, 'refs/pull/sfh/')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: solomonhawk/2022

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1.3.4

      - uses: Swatinem/rust-cache@v1
        with:
          key: v1 # increment this to bust the cache if needed

      - name: Run build
        run: cargo build --release --verbose

      - name: Run build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: AoC
        uses: actions-rs/cargo@v1
        with:
          command: aoc

  solomonhawk-test:
    if: startsWith(github.ref, 'refs/heads/sfh/') || startsWith(github.ref, 'refs/pull/sfh/')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: solomonhawk/2022

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1.3.4

      - uses: Swatinem/rust-cache@v1
        with:
          key: v1 # increment this to bust the cache if needed

      - uses: taiki-e/install-action@nextest

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --all